<a href="https://colab.research.google.com/github/abinash3103/Assignment_1/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config)

1.21.6
<function show at 0x7f85e62ed290>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
x= np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
x= np.array([2,3,4,5,6])
x.size

5

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
a=np.zeros(10)
a[5]=1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [8]:
a= np.array(range(10,50))
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [9]:
a= np.array(range(10,50))
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [11]:
a= np.array(range(0,9))
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [12]:
a=[1,2,0,4,0,0]
np.nonzero(a)

(array([0, 1, 3]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [13]:
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [15]:
a=np.random.random((3,3,3))
a

array([[[0.15276676, 0.47640837, 0.31611679],
        [0.15625176, 0.93836426, 0.52704281],
        [0.02656146, 0.136074  , 0.49995007]],

       [[0.88125879, 0.3359524 , 0.48906778],
        [0.51603986, 0.58915819, 0.80615613],
        [0.1869228 , 0.07595596, 0.54842915]],

       [[0.53557589, 0.49818941, 0.35611145],
        [0.29169304, 0.59433769, 0.07257751],
        [0.74365812, 0.8795834 , 0.86707248]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [16]:
a= np.random.random((10,10))
print(np.min(a))
print(np.max(a))
print(a)

0.020095283423624655
0.98748375313697
[[0.6737679  0.16836163 0.51374593 0.43368437 0.72191633 0.63966433
  0.45932755 0.57762254 0.20065503 0.83480506]
 [0.37325151 0.31665735 0.05513296 0.77299161 0.75034594 0.85859149
  0.42797459 0.22645071 0.7455162  0.61324713]
 [0.83908188 0.69487184 0.20723733 0.35164651 0.64648535 0.83286694
  0.13509481 0.02535911 0.54331437 0.03973151]
 [0.78180553 0.06422169 0.46225929 0.57783194 0.08123523 0.86607802
  0.28244273 0.53036488 0.51652819 0.17093408]
 [0.85984717 0.26995406 0.37308368 0.5936429  0.03248726 0.31674679
  0.21793272 0.26992026 0.28632285 0.33119055]
 [0.72401444 0.42533661 0.96187151 0.82412461 0.92037069 0.90101978
  0.53327408 0.93783013 0.89367645 0.51649225]
 [0.61254019 0.08916843 0.08718086 0.87224719 0.19983673 0.44284933
  0.88186647 0.90853938 0.45327457 0.71456508]
 [0.3645143  0.68053671 0.16691894 0.02009528 0.61593802 0.10370482
  0.38251032 0.05620039 0.98748375 0.91425019]
 [0.4078588  0.21139128 0.51920197 0.27428

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [17]:
a=np.random.rand(30)
print(np.mean(a))
print(a)

0.4327450670634186
[0.68258446 0.1592475  0.42483401 0.33800971 0.21243489 0.69102419
 0.07882246 0.51093729 0.27719467 0.21185701 0.54181808 0.14293544
 0.68488755 0.37850953 0.46142296 0.94014929 0.86000673 0.59906359
 0.65142398 0.43181647 0.53567073 0.21376374 0.20757412 0.04501429
 0.48603762 0.58177979 0.21636247 0.06951133 0.62968543 0.71797268]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [20]:
import numpy as np
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [25]:
import numpy as np
x=np.ones((5,5))
y=np.pad(x,pad_width=1,mode="constant",constant_values=0)
y

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [44]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [29]:
import numpy as np
x=np.ones((5,5))
x+=np.arange(5)
x

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [30]:
import numpy as np
x=np.zeros((3,3))
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [31]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [46]:
a=np.array([[0,1],[1,0]])
y=np.tile(a,(4,4))
y

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [33]:
x=np.random.random((5,5))
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
x

array([[0.80802076, 0.65372962, 0.94383133, 0.73763123, 0.4813731 ],
       [0.91164392, 0.17511757, 0.3073418 , 0.68215351, 0.16502353],
       [0.34525057, 0.78421315, 0.99144278, 0.50185715, 0.07070279],
       [0.28781969, 0.29407643, 0.18570763, 0.38870605, 1.        ],
       [0.26694565, 0.78593143, 0.        , 0.76282668, 0.90039523]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [34]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [35]:
x=np.dot(np.ones((5,3)),np.ones((3,2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [38]:
arr= np.arange(16)
print(arr>=3)

arr[(arr>=3)&(arr<=8)]*=(-1)
print(arr)

[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [47]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [51]:
Z=arange(10)
Z**Z
Z_2=2<<Z>>2
Z_2
print([bin(2) for z in Z_2])
print([bin(z) for z in 2 << Z_2])
print([bin(z) for z in Z_2])
Z<Z>Z

['0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10']
['0b10', '0b100', '0b1000', '0b100000', '0b1000000000', '0b100000000000000000', '0b1000000000000000000000000000000000', '0b0', '0b0', '0b0']
['0b0', '0b1', '0b10', '0b100', '0b1000', '0b10000', '0b100000', '0b1000000', '0b10000000', '0b100000000']


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [52]:
np.array ([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [53]:
arr= np.random.random((5,5))
print(arr)
arr=np.round(arr,2)
print(arr)

[[0.53070485 0.93410867 0.67125146 0.19656065 0.56814379]
 [0.8774954  0.08753948 0.40411149 0.26541639 0.67873729]
 [0.95420338 0.41347246 0.35839521 0.70985741 0.02063608]
 [0.07365925 0.13471758 0.19977654 0.92041685 0.98359125]
 [0.54151355 0.35864621 0.50650897 0.51487386 0.03878375]]
[[0.53 0.93 0.67 0.2  0.57]
 [0.88 0.09 0.4  0.27 0.68]
 [0.95 0.41 0.36 0.71 0.02]
 [0.07 0.13 0.2  0.92 0.98]
 [0.54 0.36 0.51 0.51 0.04]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [57]:
x= np.array([1,2,3,4])
y= np.array([2,3,1,5])
print(np.intersect1d(x,y))

[1 2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [58]:
import numpy as np
data = np.random.random(1000).reshape(10,10,10)*np.nan
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [59]:
np.sqrt(-1)==np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [60]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1,'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [63]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [64]:
A= np.ones(3)*1
B= np.ones(3)*2
C= np.ones(3)*3
np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [65]:
z = np.random.uniform(0,10,10)
print (Z-Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[-1.  0.  1.  2.  3.  4.  5.  6.  7.  8.]
[0 1 2 3 4 5 6 7 8 9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [66]:
x = np.zeros((5,5))
x+=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [67]:
def forma():
  for i in range(10):
    yield i
x = np.fromiter(forma(),dtype=float,count=-1)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [69]:
np.linspace(0,1,12, endpoint = True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [70]:
np.random.random(10)
x.sort()
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [72]:
a=np.random.random((5,5))
np.add.reduce(a,dtype=float)

array([2.26694846, 2.61638803, 2.85871265, 3.70522825, 2.34362299])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [74]:
x = np.random.randint(0,1,2)
y = np.random.randint(0,1,2)
e = np.allclose(x,y)
e

True

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [75]:
z= np.zeros(10)
z.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [78]:
x=np.random.random((10,2))
a,b=x[:,0],x[:,1]
y= np.sqrt(a**2+b**2)
t= np.arctan2(b,a)
y,t

(array([0.76253449, 0.89836417, 0.2947687 , 0.7046973 , 0.81114132,
        0.8872875 , 1.07553451, 0.53820111, 0.78894085, 0.83543692]),
 array([0.75689513, 0.38867986, 0.1444907 , 0.64951238, 0.99863298,
        1.50224383, 0.86695082, 0.46555148, 0.7867052 , 0.75232386]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [79]:
x=np.random.random(10)
x[x.argmax()]=0
x

array([0.29753058, 0.10293463, 0.20714117, 0.42987036, 0.        ,
       0.78982237, 0.65484385, 0.89345185, 0.56483002, 0.4088411 ])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [80]:
Y= np.random.randint(0,11,10)
X= np.random.randint(11,22,10)

y= np.tile(Y,(10,1))

X= np.tile(X,(10,1)).T

C=1/(X-Y)
C

array([[0.05263158, 0.1       , 0.11111111, 0.09090909, 0.1       ,
        0.1       , 0.05555556, 0.0625    , 0.05555556, 0.07692308],
       [0.07142857, 0.2       , 0.25      , 0.16666667, 0.2       ,
        0.2       , 0.07692308, 0.09090909, 0.07692308, 0.125     ],
       [0.07692308, 0.25      , 0.33333333, 0.2       , 0.25      ,
        0.25      , 0.08333333, 0.1       , 0.08333333, 0.14285714],
       [0.06666667, 0.16666667, 0.2       , 0.14285714, 0.16666667,
        0.16666667, 0.07142857, 0.08333333, 0.07142857, 0.11111111],
       [0.04761905, 0.08333333, 0.09090909, 0.07692308, 0.08333333,
        0.08333333, 0.05      , 0.05555556, 0.05      , 0.06666667],
       [0.0625    , 0.14285714, 0.16666667, 0.125     , 0.14285714,
        0.14285714, 0.06666667, 0.07692308, 0.06666667, 0.1       ],
       [0.07692308, 0.25      , 0.33333333, 0.2       , 0.25      ,
        0.25      , 0.08333333, 0.1       , 0.08333333, 0.14285714],
       [0.04761905, 0.08333333, 0.0909090

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [81]:
Y= np.random.randint(0,11,10)
X= np.random.randint(11,22,10)

Y= np.tile(Y,(10,1))
x= np.tile(X,(10,1)).T

C= 1/(X-Y)
C

array([[0.09090909, 0.16666667, 0.11111111, 0.1       , 0.07692308,
        0.09090909, 0.2       , 0.08333333, 0.09090909, 0.07142857],
       [0.09090909, 0.16666667, 0.11111111, 0.1       , 0.07692308,
        0.09090909, 0.2       , 0.08333333, 0.09090909, 0.07142857],
       [0.09090909, 0.16666667, 0.11111111, 0.1       , 0.07692308,
        0.09090909, 0.2       , 0.08333333, 0.09090909, 0.07142857],
       [0.09090909, 0.16666667, 0.11111111, 0.1       , 0.07692308,
        0.09090909, 0.2       , 0.08333333, 0.09090909, 0.07142857],
       [0.09090909, 0.16666667, 0.11111111, 0.1       , 0.07692308,
        0.09090909, 0.2       , 0.08333333, 0.09090909, 0.07142857],
       [0.09090909, 0.16666667, 0.11111111, 0.1       , 0.07692308,
        0.09090909, 0.2       , 0.08333333, 0.09090909, 0.07142857],
       [0.09090909, 0.16666667, 0.11111111, 0.1       , 0.07692308,
        0.09090909, 0.2       , 0.08333333, 0.09090909, 0.07142857],
       [0.09090909, 0.16666667, 0.1111111

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [83]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)   

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [84]:
Z=[]
print(Z)

[]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [85]:
arr = np.random.uniform(0,10,10)
scal =5
arr_1 = np.abs(arr-5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])

[3.27786875 7.5186653  9.1201778  1.06330965 3.1503524  1.22762573
 5.07132712 0.38669769 5.10797446 3.71939252]
************************************************************
5.0713271185000615


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [88]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [89]:
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D= np.sqrt((X-X.T)**2+(Y-Y.T)**2)

import scipy
import scipy .spatial

Z= np.random.random((10,2))
D= scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.27211646 0.49028132 0.27129473 0.18073893 0.29510615
  0.5115115  0.56482316 0.63144838 0.59864711]
 [0.27211646 0.         0.22781004 0.35661784 0.44275299 0.46195734
  0.55765633 0.35936248 0.49340407 0.43132314]
 [0.49028132 0.22781004 0.         0.56991294 0.64660225 0.68487465
  0.73997253 0.2018867  0.38743902 0.3054539 ]
 [0.27129473 0.35661784 0.56991294 0.         0.39912493 0.13406011
  0.24094397 0.71535344 0.83266704 0.7799963 ]
 [0.18073893 0.44275299 0.64660225 0.39912493 0.         0.36122946
  0.62158558 0.6833896  0.70603359 0.69305508]
 [0.29510615 0.46195734 0.68487465 0.13406011 0.36122946 0.
  0.27039888 0.81293208 0.91061101 0.86661524]
 [0.5115115  0.55765633 0.73997253 0.24094397 0.62158558 0.27039888
  0.         0.9119632  1.04943814 0.98895773]
 [0.56482316 0.35936248 0.2018867  0.71535344 0.6833896  0.81293208
  0.9119632  0.         0.19159476 0.10710755]
 [0.63144838 0.49340407 0.38743902 0.83266704 0.70603359 0.91061101
  1.04943814 0.19159

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [90]:
Z= np.arange (10,dtype=np.float32)
Z_1 = Z.astype(np.float32, copy= False)
Z_1[0] =2
print(Z)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [94]:
from io import stringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

ImportError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [95]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
  print(index, value)
for index in np.ndindex(Z.shape):
  print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [98]:
sigma,myu = 1.0,0.0

X,Y = np.meshgrid(np.linspace (-1,1,10),np.linspace(-1,1,10))
D= np.sqrt(X**2+Y**2)
G= np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [99]:
n= 10
p= 3 
Z = np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)

np.put(Z,11,1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [6]:
import numpy as np
X= np.random.rand (5,10)
Y= X-X.mean(axis =1 ,keepdims = True)

X.mean (axis=1).reshape(-1,1) == X.mean(axis =1, keepdims= True)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [7]:
Z= np.random.randint(0,10,(5,5))
print(Z)

print(Z[(-Z)[:,1].argsort()])
print(Z[:,Z[1,:].argsort()])

[[4 3 4 5 5]
 [4 4 0 1 3]
 [0 7 7 3 4]
 [0 9 1 7 9]
 [0 1 7 5 6]]
[[0 9 1 7 9]
 [0 7 7 3 4]
 [4 4 0 1 3]
 [4 3 4 5 5]
 [0 1 7 5 6]]
[[4 5 5 4 3]
 [0 1 3 4 4]
 [7 3 4 0 7]
 [1 7 9 0 9]
 [7 5 6 0 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [8]:
Z= np.random.randint(0,3,(3,10))
Z[:,1]=0
Z=Z.astype(bool)
print(Z)
print(~Z)
(Z).any (axis=0)

[[False False  True False  True  True False False False  True]
 [False False  True  True  True  True  True False  True  True]
 [False False  True  True False  True False  True  True  True]]
[[ True  True False  True False False  True  True  True False]
 [ True  True False False False False False  True False False]
 [ True  True False False  True False  True False False False]]


array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [12]:
A= np.arange(3).reshape(3,1)
B= np.arange(3).reshape(1,3)
it= np.nditer ([A,B,None])
for x,y,z in it: z[...]= x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [13]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [15]:
Z = np.ones(10)
I= np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength= len(Z))
print(Z)
np.add.at(Z,I,1)
print(Z)

[3. 4. 3. 5. 4. 1. 1. 4. 3. 2.]
[5. 7. 5. 9. 7. 1. 1. 7. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [16]:
X= [1,2,3,4,5,6]
I= [1,3,5,9,2,1]
F= np.bincount(I,X)
print(F)

[0. 7. 5. 2. 0. 3. 0. 0. 0. 4.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [17]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

I24 = np.dot(I.astype(np.uint32),[1,256,65536])

n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [23]:
A = np.random.randint(0,10,(3,4,3,4)) 
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[48 74 61 38]
 [49 54 45 67]
 [59 71 68 56]]
[[48 74 61 38]
 [49 54 45 67]
 [59 71 68 56]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [31]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts= np.bincount(S)
D_means = D_sums/D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.44875562 0.64639934 0.56862604 0.50511987 0.5436084  0.48772038
 0.63561356 0.5954765  0.5785606  0.63854531]
0    0.448756
1    0.646399
2    0.568626
3    0.505120
4    0.543608
5    0.487720
6    0.635614
7    0.595476
8    0.578561
9    0.638545
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [33]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


array([2.25481832, 1.2051091 , 1.19733862, 0.87577723, 0.79938972])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [34]:
Z = np.array ([1,2,3,4,5])
nz=3
Z0 = np.zeros(len(Z)+(len(Z)-1)*(nz))
Z0[::nz+1]=Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [2]:
import numpy as np
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [3]:
A=np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [4]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 54) ( 1, 58) ( 1, 79) ( 1, 95) ( 4, 97) ( 4, 98) ( 5, 15) ( 5, 33)
 ( 5, 77) ( 5, 99) (10, 76) (10, 97) (15, 99) (20, 32) (20, 36) (24, 55)
 (24, 62) (28, 90) (28, 96) (31, 83) (31, 84) (32, 36) (33, 77) (54, 95)
 (55, 62) (58, 79) (76, 97) (83, 84) (90, 96) (97, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [5]:
C=np.bincount([1,1,2,3,4,5,6,])
A=np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 5 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [6]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [7]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [9]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.13614381,  0.04250954,  0.31495739, -0.63477312, -0.54729024,
        0.38780754, -0.07319948,  0.85969685,  0.52892098, -0.52325192,
       -0.82852768, -0.3141815 , -0.91214084, -0.12776144,  0.43322399,
       -0.61564409, -0.28446677, -0.05578457, -0.3996344 , -0.50815104,
        0.32558779, -0.81612777, -0.14628256,  0.90179099, -0.77929407,
       -0.28763563,  0.5638387 , -0.63181408,  0.30395232,  0.1291865 ,
       -0.6750645 , -0.78726454,  0.62595804,  0.86136219,  0.53306855,
        0.77717398,  0.76029165,  0.93629851,  0.30221043, -0.54343592,
        0.60934636, -0.43024756,  0.94694677,  0.69764305, -0.27168462,
       -0.43136044,  0.74006983,  0.09715434, -0.0443938 ,  0.66680355,
        0.97287322, -0.1242043 ,  0.88321365, -0.68108222,  0.36793801,
       -0.59099971, -0.1352144 , -0.4597476 ,  0.10350073,  0.30929497,
       -0.88981221,  0.27938798, -0.32969959,  0.52455953, -0.99908444,
        0.058503  , -0.99370715, -0.39979224,  0.78403914,  0.38

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [10]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 7.24793852  0.73579062  4.9855377  11.17604469  2.99452371  7.15140993
  7.24651152  8.32148644  0.53728729  4.58260737]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [14]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10, 10,(10,2))
P = np.random.uniform(-10,10,(10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.87463035 12.19892172  9.95620331  9.57950616  8.82856342  7.19918657
   1.28785513  3.9932748   4.63737504  2.80417219]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [15]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 4 8 1 6 9 4 3 7 8]
 [2 4 0 0 7 8 3 5 8 3]
 [6 6 7 3 9 0 1 2 7 9]
 [7 1 1 4 4 5 1 9 6 5]
 [5 1 2 6 7 3 3 7 7 2]
 [7 6 1 7 4 7 6 5 9 2]
 [5 5 5 2 2 9 8 5 5 7]
 [6 0 2 2 4 9 7 8 6 1]
 [6 5 6 2 9 6 7 1 9 4]
 [8 2 1 1 5 2 7 2 4 6]]
[[0 0 0 0 0]
 [0 2 4 8 1]
 [0 2 4 0 0]
 [0 6 6 7 3]
 [0 7 1 1 4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [34]:
import numpy as np
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


NameError: ignored

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [9]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [10]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [17]:
import sys
import numpy as np
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C =np.lib. stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[3 3 1]
   [2 2 3]
   [0 4 2]]

  [[3 1 3]
   [2 3 2]
   [4 2 3]]

  [[1 3 4]
   [3 2 1]
   [2 3 0]]

  [[3 4 3]
   [2 1 2]
   [3 0 2]]

  [[4 3 4]
   [1 2 1]
   [0 2 1]]

  [[3 4 4]
   [2 1 3]
   [2 1 0]]

  [[4 4 3]
   [1 3 1]
   [1 0 4]]

  [[4 3 0]
   [3 1 0]
   [0 4 2]]]


 [[[2 2 3]
   [0 4 2]
   [0 0 0]]

  [[2 3 2]
   [4 2 3]
   [0 0 2]]

  [[3 2 1]
   [2 3 0]
   [0 2 0]]

  [[2 1 2]
   [3 0 2]
   [2 0 0]]

  [[1 2 1]
   [0 2 1]
   [0 0 0]]

  [[2 1 3]
   [2 1 0]
   [0 0 3]]

  [[1 3 1]
   [1 0 4]
   [0 3 3]]

  [[3 1 0]
   [0 4 2]
   [3 3 4]]]


 [[[0 4 2]
   [0 0 0]
   [0 3 4]]

  [[4 2 3]
   [0 0 2]
   [3 4 2]]

  [[2 3 0]
   [0 2 0]
   [4 2 4]]

  [[3 0 2]
   [2 0 0]
   [2 4 2]]

  [[0 2 1]
   [0 0 0]
   [4 2 1]]

  [[2 1 0]
   [0 0 3]
   [2 1 3]]

  [[1 0 4]
   [0 3 3]
   [1 3 1]]

  [[0 4 2]
   [3 3 4]
   [3 1 0]]]


 [[[0 0 0]
   [0 3 4]
   [4 2 4]]

  [[0 0 2]
   [3 4 2]
   [2 4 0]]

  [[0 2 0]
   [4 2 4]
   [4 0 3]]

  [[2 0 0]
   [2 4 2]
   [0 3 2]]

  [[0 0 0]
   

NameError: ignored

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [22]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  8 12 11  4]
 [ 8  6  7  7  0]
 [12  7  7 42  3]
 [11  7 42  6 12]
 [ 4  0  3 12  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [30]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [50]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)
Z = np.ones((16,16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


NameError: ignored

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [35]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [36]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [37]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [38]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [39]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.79 s ± 17.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
138 ms ± 2.23 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
149 ms ± 15.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [40]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [42]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 4 1]
 [3 0 4]
 [0 4 2]
 [3 3 3]
 [1 3 3]
 [4 1 2]
 [3 4 2]
 [2 1 4]
 [1 1 4]
 [3 0 1]]
[[2 4 1]
 [3 0 4]
 [0 4 2]
 [1 3 3]
 [4 1 2]
 [3 4 2]
 [2 1 4]
 [1 1 4]
 [3 0 1]]
[[2 4 1]
 [3 0 4]
 [0 4 2]
 [1 3 3]
 [4 1 2]
 [3 4 2]
 [2 1 4]
 [1 1 4]
 [3 0 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [43]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [44]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]
[[0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [45]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)      
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.03503871, 0.06401026, 0.00502157, 0.02272975, 0.03137391,
        0.06743835, 0.0719901 , 0.04263652, 0.06224412, 0.0487045 ],
       [0.37507056, 0.68519545, 0.05375318, 0.24330976, 0.33584089,
        0.72189134, 0.77061539, 0.45640107, 0.66628992, 0.52135557],
       [0.39873284, 0.72842275, 0.05714433, 0.25865958, 0.35702827,
        0.76743369, 0.81923163, 0.48519429, 0.70832452, 0.55424662],
       [0.43612885, 0.79673944, 0.06250374, 0.28291852, 0.39051293,
        0.83940911, 0.89606502, 0.53069928, 0.77475625, 0.60622783],
       [0.05347327, 0.09768733, 0.00766351, 0.03468832, 0.04788035,
        0.10291901, 0.10986553, 0.06506845, 0.094992  , 0.07432892],
       [0.35348473, 0.64576151, 0.05065961, 0.22930695, 0.31651278,
        0.6803455 , 0.72626542, 0.43013456, 0.62794402, 0.49135084],
       [0.0082655 , 0.01509978, 0.00118457, 0.00536186, 0.00740099,
        0.01590846, 0.0169822 , 0.0100578 , 0.01468316, 0.01148921],
       [0.05145924, 0.09400801, 0.0073748

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [47]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [48]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [49]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.11441546  0.33108027]
